### ISSUE TITLE
PDF piscine

### ISSUE THREAD

**Issue by hezirel** [arnauddrain/epitech#1]
Bonjour,

Me serait il possible de te demander les pdf de tout les jours de la piscine stp ? J'en ai vu quelques un et ils ont l'air challenging and intéressant. Mais je n'ai pas envie de payer 7K€ pour y accéder.

Pourrait tu me les envoyer ?

**Comment by arnauddrain** [comment]
Hello,

Tu trouveras très facilement sur GitHub les sujets de la piscine de 42, ce sont les mêmes avec un design différent.

Je te confirme qu'ils sont intéressants ;)

**Comment by hezirel** [comment]
Merci du tuyau !
